version: '3.8'

services:
  web:
    image: skytechmk/anunnaki-web:latest
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped
